### ISSUE TITLE
reactish-state <> typescript

### ISSUE THREAD

**Issue by Nishchit14** [szhsin/reactish-state#23]
I just want to say, **This is an amazing state management library**. I see great potential here.

For now, I have only two questions
1. How to use it with typescript? If I have a store of long nested objects/states.
2. Can I create the dynamic store/state with a key? 
     - For example, I have multiple tabs, and when I open a tab It'll create a dedicated store/state in the parent. It will get destroyed when I'll close the tab.
     
  Thank you for the great work!!

**Comment by szhsin** [comment]
@Nishchit14 , thanks for your feedback. I'm glad to hear that you love this library.

Typescript usage relies on type inference and the code would be very similar to JavaScript. Let's say we have a state that holds an array of `Todo` objects:
```ts
interface Todo {
  id: number;
  text: string;
  isCompleted: boolean;
}
```
We can create a state by providing an initial value:
```ts
const initialTodos: Todo[] = [];
const todoListState = state(initialTodos);
```
or
```ts
const todoListState = state([] as Todo[]);
```
Then `get` and `set` will have inferred types:
```ts
todoListState.get(); // return type is Todo[]
todoListState.set([{ id: 1, isCompleted: false, text: 'new' }]); // Accepts Todo[] as parameter
```
The actions of a state can also be inferred:
```ts
const todoListState = state([] as Todo[], (set) => ({
  addItem: (text: string) =>
    set((todos) => [...todos, { id: Date.now(), text, isCompleted: false }])
}));

todoListState.actions.addItem('new task') // addItem: (text: string) => void
```

`selector` supports type inference as well:
```ts
type VisibilityFilter = 'ALL' | 'ACTIVE' | 'COMPLETED';
const visibilityFilterState = state('ALL' as VisibilityFilter);

const visibleTodoList = selector(
  todoListState,
  visibilityFilterState,
  (
    todoList /* inferred type: Todo[] */,
    visibilityFilter /* inferred type: 'ALL' | 'ACTIVE' | 'COMPLETED' */
  ) => {
    // ...
  }
);
```
You can find [the example here](https://github.com/szhsin/reactish-state/blob/master/examples/examples/todo/store.ts). The library itself and all examples are written in TypeScript.

**Comment by szhsin** [comment]
For the dynamic tab state, you may have something like:
```ts
interface Tab {
  id: number;
  name: string;
  // more fields ...
}

interface Tabs {
  [key: string]: Tab;
}

const tabs = state({} as Tabs, (set) => ({
  addTab: (key: string, tab: Tab) => set((tabs) => ({ ...tabs, [key]: tab })),
  removeTab: (key: string) =>
    set((tabs) => {
      // Need immer middleware for the mutation to work
      delete tabs[key];
      return tabs;
    })
}));
```
Then call the `addTab` or `removeTab` actions when tab components mount or unmount.

**Comment by Nishchit14** [comment]
That's great, thank you for sharing the examples.

As you have created the `tabs` state, If I've three tabs opened and change something in the last tab then It'll only re-render the last tab or re-render effect will happen in all tabs?

Also I see that the package has a peer dependency `immer`. so It is dependant on `immer` or it's optional?

**Comment by Nishchit14** [comment]
what is the use of the `key` here? https://github.com/szhsin/reactish-state/blob/master/examples/examples/todo/store.ts#L43 I didn't see anything in the doc.

**Comment by szhsin** [comment]
> As you have created the `tabs` state, If I've three tabs opened and I change something in the last tab then It'll only re-render the last tab or re-render effect will happen in all tabs? I am concerned about the render optimization.

If tab data is read from the `tabs` state using `useSnapshot` in a tab component, a change in one tab will cause all other tabs to re-render, because `tabs` holds data for all three tabs.
```ts
const Tab = () => {
  const tab = useSnapshot(tabs)[key];
};
```
Currently the recommend way for render optimization in this case is to use a selector to extract the specific tab data for the component:
```ts
const Tab = () => {
  const tab = useSnapshot(selector(tabs, (tabs) => tabs[key]));
};
``` 

> Also I see that the package has a peer dependency `immer`. so It is dependant on `immer` or it's optional?

It's optional, only if you need to use the immer middleware: 
```ts
import { immer } from 'reactish-state/middleware/immer';
```

> what is the use of the `key` here?

The `key` gives each state a bit of context. Currently it's used by `persist` middleware to persist data in browser storage, and by `reduxDevtools` middleware to aggregate individual state into one big store for display in dev tools.

The `key` is optional if those two middleware are not used.
